guidelines: add pull requests section
rero/developer-resources pull request #3
Opened 2020-04-29 05:52 UTC by jma

Co-Authored-by: Johnny Mariéthoz <Johnny.Mariethoz@rero.ch>

2020-04-29 05:56 UTC, iGormilhit approved these changes

2020-04-29 09:20 UTC, blankoworld commented on guidelines/pull-rquests.md
> +1. Call the first reviewer
During the sprint retrospective we talk about a sub-task something like `check regularly that the reviewer is available for review, change it if needed`.
What do you think?

2020-04-29 09:22 UTC, blankoworld commented
Example of link I want to see: rero/rero-ils-ui#253

2020-04-29 09:53 UTC, iGormilhit requested changes
Could you move the existing guidelines from the rero-ils `CONTRIBUTING.rst` file to your modification in this repository?
https://github.com/rero/rero-ils/blob/master/CONTRIBUTING.rst#pull-request-guidelines
Then we will have to update the `CONTRIBUTING.rst` file in our different projects.

2020-05-19 05:43 UTC, iGormilhit approved these changes

2020-05-19 05:53 UTC, merged